### ISSUE TITLE
pandoc-citeproc-bin has been removed from AUR

### ISSUE THREAD

**Issue by jannes-m** [rbind/pat-s_web#3]
Hey Pat,
first of all, thanks for this fantastic guide which I have been using a lot. Without it, I probably would have never started to use Arch in the first place...

`pandoc-citeproc-bin` has been removed from AUR (see e.g., comments found on https://aur.archlinux.org/packages/pandoc-bin/). The only way I found to make `community/pandoc-citeproc 0.16.2-90` working, was to install `community/pandoc 2.7.3-23` instead of `aur/pandoc-bin 2.7.3-1 [99+] [2.50%] [3 Jul 2019]`. I think this might be the better solution compared to manually clone the `pandoc-citeproc-bin` git repository as proposed in the comments found on https://aur.archlinux.org/packages/pandoc-bin/. Please note that the installation size of `community/pandoc` now is only 170MB, not 1GB anymore.

**Comment by pat-s** [comment]
Thanks, I've updated the post. This was long overdue anyways.

`community/pandoc` still uses all the haskell dependencies and is several 100 MB large. 
But right now it seems that there is no really a convenient second option.

Thanks for the pointer and great it helped you :)
